config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :recipes, only: [:index, :show] do
    resources :user_recipes, only: [:create]
    resources :shopping_ingredients, only: [:create]
  end

  resources :user_recipes, only: [:update, :destroy]

  resources :shopping_lists, only: :update

  resources :ingredients, only: :update

  resources :shopping_ingredients, only: [:update]

  get "/cart", to: "user_recipes#cart", as: :cart
  get "/cookbook", to: "user_recipes#cookbook", as: :cookbook
  get "/list", to: "shopping_lists#show", as: :list
  get "/search", to: "recipes#search", as: :search
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_one_attached :photo
  has_many :ingredients, dependent: :destroy
  has_many :foods, through: :ingredients
  has_many :user_recipes, dependent: :destroy
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @user_recipe = UserRecipe.new

    if params[:meal_type].present?
      @recipes = policy_scope(Recipe).where.not(id: current_user.recipes).where(meal_type: params[:meal_type]).where("cooking_time <= ?", params[:time]).order(cooking_time: :asc)
    elsif params[:query].present?
      @user_recipes = Recipe.all
      authorize @user_recipes
      sql_query = <<~SQL
        recipes.name ILIKE :query
        OR foods.name ILIKE :query
      SQL
      @recipes = policy_scope(Recipe).joins(:foods).distinct.where(sql_query, query: "%#{params[:query]}%")
    else
      @recipes = policy_scope(Recipe).where.not(id: current_user.recipes).where(meal_type: "lunch")
    end

    if params[:recipe]
      top_recipe = @recipes.find { |recipe| recipe.id == params[:recipe].to_i }
      @recipes.delete_at(@recipes.index(top_recipe))
      @recipes << top_recipe
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
    authorize @recipe
    @shopping_ingredient = ShoppingIngredient.new
  end

  def search
    @user_recipes = Recipe.all
    authorize @user_recipes
    if params[:query].present?
      sql_query = <<~SQL
        recipes.name ILIKE :query
        OR foods.name ILIKE :query
      SQL
      @user_recipes = Recipe.joins(:foods).distinct.where(sql_query, query: "%#{params[:query]}%")

    end
  end
end

app/views/recipes/index.html.erb
<!--put searchbar here-->
<div class="standart-container">
  <div class="searchbar-fm">
    <%= form_with url: recipes_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
                         params[:query],
                         class: "form-control border-0 bg-light font-size",
                         placeholder: "Search by recipe or ingre..." %>
      <button type="submit" class="search-btn">
        <i class="fa fa-search font-color"></i>
      </button>
    <% end %>
  </div>
</div>
<ul class="stack standard-container" data-controller="swinger">
  <%# move the next line to the controller %>
  <%# where("meal_type = ? AND cooking_time <= ?", params[:meal_type], params[:time]). %>
  <% @recipes.limit(20).each do |recipe| %>
    <li class="child" data-swinger-target="card">
      <%= render "shared/cards/dish",
                 name: recipe.name,
                 cuisine: recipe.cuisine_type,
                 time: recipe.cooking_time,
                 image: recipe.photo.key,
                 recipe: recipe %>
    </li>
  <% end %>
</ul>

app/views/recipes/search.html.erb
<div class="standard-container">
  <div class="standard-container mt-5 w-100">
    <%= form_with url: search_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
                         params[:query],
                         class: "form-control",
                         placeholder: "Find a recipe"
      %>
      <%= submit_tag "Search", class: "btn btn-primary" %>
    <% end %>
  </div>
  <div class="search results cart-size-extra mt-3">
    <% if params[:query].present? %>
      <% if @user_recipes.blank? %>
        No Results
      <% else %>
        <ul>
          <% @user_recipes.each do |recipe| %>
            <div data-controller="card-actions" class="cart-search-extra">
              <%= link_to "/recipes/#{recipe.name}", class: "cart-link" do %>
                <%= cl_image_tag recipe.photo.key, class: "cart-recipe-img" %>
              <% end %>
              <div class="d-flex flex-column justify-content-between">
                <p class="cart-recipe-name w-100 "><%= recipe.name %></p>
                <div class="ps-2">
                  <i class="fa-solid fa-clock"></i> Cooking Time <%= recipe.cooking_time %>
                  <p><i class="fa-solid fa-earth-europe"></i> Cuisine <%= recipe.cuisine_type.capitalize %>
                  </p>
                </div>
              </div>
            </div>
          <% end %>
        </ul>
      <% end %>
    <% end %>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="standard-container recipe-container white">
  <div class="flex-container">
    <div class="recipe-img-container d-flex justify-content-center">
      <%= cl_image_tag @recipe.photo.key, class: "recipe-img" %>
      <div class="back-link">
        <%= link_to "javascript:history.back()" do %>
          <i class="fa-solid fa-angles-left"></i>
        <% end %>
      </div>
    </div>
    <div class="recipe-info">
      <h1 class="recipe-name"><%= @recipe.name %></h1>
      <div class="recipe-categories">
        <p>
          <span><i class="fa-solid fa-clock"></i></span>
          <%= "#{@recipe.cooking_time} mins" %>
        </p>
        <p>
          <span><i class="fa-solid fa-fire"></i></span>
          <%= "#{@recipe.calories.to_i / @recipe.yield} cals" %>
        </p>
        <p>
          <span><i class="fa-solid fa-bowl-rice"></i></span>
          <%= "#{@recipe.yield} portions" %>
        </p>
      </div>
      <div class="ingredients">
        <div class="ingredients-title d-flex justify-content-between align-items-center">
          <h2>Ingredients</h2>
          <%= render "shared/buttons/add_recipe_button" if params[:showbutton] == "show" %>
        </div>
        <div class="ingredients-list">
          <ul>
            <% @recipe.ingredients.each do |ingredient| %>
              <li>
                <% ingredient_mod = ingredient.food.name.split %>
                <% ingredient_mod.map do |word| %>
                  <% word.capitalize! %>
                <% end %>
                <% ingredient_mod = ingredient_mod.join(" ") %>

                <span class="ingredient"><%= ingredient_mod %></span>
                <span><%= ingredient.quantity.truncate(1) %></span>
                <% if ingredient.measure != "<unit>" %>
                  <span><%= ingredient.measure %>s</span>
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <%= link_to "#{@recipe.url}", class: '' do %>
      <div class="recipe-source">
        <span>Recipe</span>
      </div>
    <% end %>
  </div>
</div>