config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :recipes, only: [:index, :show] do
    resources :user_recipes, only: [:create]
    resources :shopping_ingredients, only: [:create]
  end

  resources :user_recipes, only: [:update, :destroy]

  resources :shopping_lists, only: :update

  resources :ingredients, only: :update

  resources :shopping_ingredients, only: [:update]

  get "/cart", to: "user_recipes#cart", as: :cart
  get "/cookbook", to: "user_recipes#cookbook", as: :cookbook
  get "/list", to: "shopping_lists#show", as: :list
  get "/search", to: "recipes#search", as: :search
end

app/views/shared/cards/_dish.html.erb
<div class="standard-container">
  <div class="dish-container">
    <div class="dish" data-controller="card-actions">
      <%= link_to recipe_path(recipe) do %>
        <%= cl_image_tag image, class: "dish-image" %>
      <% end %>
      <div class="dish-description">
        <div class="dish-name">
          <h2><%= link_to recipe.name, recipe_path(recipe) %></h2>
        </div>
        <div class="dish-items ">
          <div class="dish-item">
            <i class="fa-solid fa-bowl-rice"></i>
            <span><%= "#{recipe.yield} portions" %></span>
          </div>
          <div class="dish-item">
            <i class="fa-solid fa-clock"> </i>
            <span><%= time %> mins</span>
          </div>
          <div class="dish-item">
            <i class="fa-solid fa-fire"></i>
            <span><%= "#{recipe.calories.to_i / recipe.yield.to_i} cals" %></span>
          </div>
        </div>


      </div>
      <div class="cart-button">
        <%= render "shared/buttons/cart", link: "/cart",
                   counter: UserRecipe.where(user: current_user, saved: false).count %>
      </div>


      <div class="d-flex justify-content-around px-2 mb-3">
        <div class="button pass neumorph-card-button"
             data-action="click->swinger#choose" data-swinger-like-param="false">
          <span class="button-text"><i class="fa-solid fa-xmark"></i></span>
        </div>
        <div class="button-form neumorph-card-button" data-action="click->swinger#choose"
             data-swinger-like-param="true">
          <%= simple_form_for [recipe, @user_recipe], html: { data: { swinger_target: "form" } } do |f| %>
            <button type="submit" class="like">
              <i class="fa-solid fa-heart"></i>
            </button>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>