config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :recipes, only: [:index, :show] do
    resources :user_recipes, only: [:create]
    resources :shopping_ingredients, only: [:create]
  end

  resources :user_recipes, only: [:update, :destroy]

  resources :shopping_lists, only: :update

  resources :ingredients, only: :update

  resources :shopping_ingredients, only: [:update]

  get "/cart", to: "user_recipes#cart", as: :cart
  get "/cookbook", to: "user_recipes#cookbook", as: :cookbook
  get "/list", to: "shopping_lists#show", as: :list
  get "/search", to: "recipes#search", as: :search
end

app/models/shopping_list.rb
class ShoppingList < ApplicationRecord
  belongs_to :user
  has_many :shopping_ingredients
  has_many :ingredients, through: :shopping_ingredients
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController
  def show
    @list = current_user.current_shopping_list
    authorize @list
    @recipes = @list.shopping_ingredients.group_by { |si| si.ingredient.recipe.name}
  end

  def update
    @shopping_list = ShoppingList.find(params[:id])
    authorize @shopping_list
    if @shopping_list.update(shopping_list_params)
      redirect_to "/cookbook", notice: "Emptied your shopping list!"
    else
      render :edit
    end
  end

  private

  def shopping_list_params
    params.require(:shopping_list).permit(:completed)
  end
end

app/views/shopping_lists/show.html.erb
<div class="standard-container accordion">
  <div class="page-name">
    <p>Shopping List</p>
  </div>
  <div class="show-spacing content-bx">
    <% @recipes.each do |recipe_name, shopping_ingredients| %>
      <div data-controller="accordion">
        <div class="accordion-label" data-action="click->accordion#collapse">
          <p class="list-item-name d-flex ">
            <span class="pe-1"><i class="fa-solid fa-chevron-right pe-2 arrow" data-accordion-target="arrow"></i></span>
            <span><%= recipe_name %></span>
          </p>
        </div>
        <div class="accordion-content mb-3" data-accordion-target="content">
          <% shopping_ingredients.sort_by(&:created_at).each do |shopping_ingredient| %>
            <div class="list-item accordion-content">
              <div class="d-flex align-items-center check-item ingredient-line">
                <%= form_for(shopping_ingredient, class: "form-control") do |f| %>
                  <%= f.check_box :bought, as: :boolean, onclick: "this.form.submit()", class: "list" %>
                <% end %>
                <span class="ms-3 mb-2 ll-text">
                  <%= shopping_ingredient.ingredient.food.name.capitalize %>:
                  <%= shopping_ingredient.ingredient.quantity.round(2) %>
                  <%= shopping_ingredient.ingredient.measure if shopping_ingredient.ingredient.measure != "<unit>" %>
                </span>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <%= render "shared/buttons/archive", current_list: @list if current_user.current_shopping_list.shopping_ingredients[0] != nil %>
  <% if @list.shopping_ingredients.all.count == 0 %>
    <div class="no-info">
      <p class="text">No ingredients on your Shopping List yet.</p>
      <p class="text">Select one from your Cookbook to add it!</p>
    </div>
    <div class=" pt-3">
      <%= link_to "#{cookbook_path}", class: 'button-link' do %>
        <div class="archive-button archive-button-green d-flex justify-content-center">
          <span class="">To Cookbook</span>
        </div>
      <% end %>
    </div>
  <% end %>
</div>